-- V1__init_schema.sql
-- Initial schema for SynergyEventSphere. Mirrors the JPA entity model
-- in com.ses.ems.model so Hibernate's `ddl-auto: validate` succeeds.
--
-- Notes:
--   * `LocalDateTime` columns are mapped to `timestamp` (without time zone).
--   * `Instant`       columns are mapped to `timestamp with time zone`,
--     matching Hibernate 6's default for java.time.Instant on PostgreSQL.
--   * Identity primary keys use the SQL-standard `GENERATED BY DEFAULT
--     AS IDENTITY` (PostgreSQL 10+), which is what Hibernate 6 emits for
--     `GenerationType.IDENTITY`.

CREATE TABLE users (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    contact_no  VARCHAR(20),
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE venues (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    location    VARCHAR(255) NOT NULL,
    capacity    INTEGER      NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE TABLE events (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(150) NOT NULL,
    description        TEXT,
    date_time          TIMESTAMP    NOT NULL,
    organizer_id       BIGINT       NOT NULL,
    venue_id           BIGINT,
    custom_venue_name  VARCHAR(150),
    custom_location    VARCHAR(255),
    capacity           INTEGER      NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    CONSTRAINT fk_events_organizer
        FOREIGN KEY (organizer_id) REFERENCES users (id),
    CONSTRAINT fk_events_venue
        FOREIGN KEY (venue_id)     REFERENCES venues (id)
);

CREATE TABLE bookings (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    event_id      BIGINT      NOT NULL,
    status        VARCHAR(20) NOT NULL,
    booking_time  TIMESTAMP,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT uk_booking_user_event UNIQUE (user_id, event_id),
    CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id)  REFERENCES users  (id),
    CONSTRAINT fk_bookings_event
        FOREIGN KEY (event_id) REFERENCES events (id)
);

-- Backs the per-event capacity check
-- (COUNT bookings WHERE event_id = ? AND status = 'BOOKED') with an
-- index-only scan. Mirrors @Index(name = "idx_bookings_event_status").
CREATE INDEX idx_bookings_event_status
    ON bookings (event_id, status);

CREATE TABLE user_sessions (
    id          BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  VARCHAR(64)              NOT NULL,
    user_id     BIGINT                   NOT NULL,
    active      BOOLEAN                  NOT NULL,
    issued_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at  TIMESTAMP WITH TIME ZONE,
    user_agent  VARCHAR(255),
    ip_address  VARCHAR(64),
    created_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_user_sessions_session_id UNIQUE (session_id),
    CONSTRAINT fk_user_sessions_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX idx_user_sessions_session_id
    ON user_sessions (session_id);
CREATE INDEX        idx_user_sessions_user_id
    ON user_sessions (user_id);
